### ISSUE TITLE
Error Messages on UUIDS is wrong

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere#290]
When accessing UUIDs that don't exist or don't have access to, return a generic 404

**Comment by whereismyjetpack** [comment]
![Screen Shot 2020-05-08 at 11 06 15 AM](https://user-images.githubusercontent.com/3694886/81419247-f643bb80-911b-11ea-8d12-fa4cc5c0943b.png)


When throwing ` Pundit::NotAuthorizedError` we should return a 401

**Comment by awead** [comment]
Fixed in 635f957d6f5e203794a3ac804e46dd04d2f2cc4e
