### ISSUE TITLE
Works with duplicate file names

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere#325]
Several works have files sharing the same names. It is not clear if the files themselves are identical or just have the same name but different content.

These are not being migrated because we don't allow duplicate files. We could either skip them, rename them, or fix them in Scholarsphere 3.

| Work | Duplicates? | Status |
| ----- | ------------ | ------ |                                   
| https://scholarsphere.psu.edu/concern/generic_works/sj3860860x | identical files with different names | ✅                                                
| https://scholarsphere.psu.edu/concern/generic_works/9s4655g25h | unknown | ✅

**Comment by DanCoughlin** [comment]
Append a sequence number to the copy files, sort by date and we will give privilege to the most recent copy.

**Comment by awead** [comment]
It's going to be easier just to allow duplicate filenames in the migration. We're using a similar pattern elsewhere when we validate works differently in the context of a migration versus the UI. See 47b107f71cbb64c6a0f6ddf46258460e7d7e4e1c

**Comment by awead** [comment]
## Proposal

Over half of these are works that contain identical (i.e. the same checksum) files. Others are either different versions of a file with the same name, of some other unique scenarios.

I propose that we delete the files that are identical at the checksum level, and investigate the remaining works individually. It's going to be much easier if we can delete or rename duplicate file sets in Scholarsphere 3 than it will be to engineer a process to migrate them in their current state.

**Comment by srerickson** [comment]
@awead, I don't understand why "identical files with different names" would fail on migration.

**Comment by srerickson** [comment]
I *think* I've fixed all these, but we won't know until after the next migration.

**Comment by awead** [comment]
Ok. it's all fixed now. The issue with the last two was that there were some hidden file sets. Duplicates that were there, but somehow not displayed. I removed these duplicated and re-migrated them.
