### ISSUE TITLE
Azure Groups Discrepancy

### ISSUE THREAD

**Issue by whereismyjetpack** [psu-stewardship/scholarsphere#411]
The `.owner` and `.admin` groups within ldap are _not_ represented in azure token, or graph api groups. as well as some other groups. 

Currently we have edit acls on the following groups that are _not_ coming out of the graph api
```
umg-personal.cam156.access_to_my_docs
umg-psu.nursing.simulations.admin
umg-up.emsl.staff.admin
umg-up.emsl.staff.owner
```

Currently we have read acls on the following groups that are _not_ coming out of the graph api
```
umg-psu.nursing.simulations
umg-psu.nursing.simulations.admin
umg-up.lps.augmented_learning_research_group
umg-up.lps.augmentedlearnin
```

If we launch with Azure AD, and leave the acls as such, members of those groups will stop maching, and stop having access (presumably owners will retain access) @awead ?

It seems that groups that aren't synced into o365, .admin, .owner, and -personal groups are not part of the _new_ group system. How should we migrate these ACLs? I don't see an automated way of dealing with these discrepancies. I see 3 options:

1.) migrate them as is, and let the users discover they no longer have  access. 
2.) contact the users ahead of time, and have them create new standard, synced (non .admin .owner) groups for this use case and we can make that mapping after migration
3.) we don't launch with Azure AD, and presumably run into this issue when we are forced to :)

**Comment by whereismyjetpack** [comment]
The other difference that I will document here, just so we don't forget is that the shape of groups is slightly different. For migration we'll have to transform the groups in the existing database

i.e
```
"umg/foo".gsub('/','-')
```

**Comment by awead** [comment]
The issues with read acls will be rendered moot by the fact that everything is viewable and downloadable by Penn State users. The edit acls can be dealt with on a case-by-case basis, but I think the basic plan is migrate everything as-is and then edit the group names post-migration to reflect what's coming out of Azure. We really only have two groups to deal with: umg-psu.nursing.simulations and umg-up.emsl.staff. The first one looks like something Carolyn Cole (cam156) had done probably for testing. I don't think we need the "admin" vs. "owner" distinction. We just need a group to identify as the editors for these resources. I think that's something @srerickson could ask them about.

**Comment by awead** [comment]
Here's an example from the "emsl" group https://scholarsphere.psu.edu/concern/generic_works/n02870z134
and ones from nursing appear to be private https://scholarsphere.psu.edu/concern/generic_works/5t34sj73g so those will migrated in a "draft" status.

**Comment by whereismyjetpack** [comment]
The only issue is that the .admin and .owner groups do have different members, so the user may need to be informed of this change.

**Comment by awead** [comment]
We're good. We'll handle it when/if we need to.
