### ISSUE TITLE
Do we want a favicon?

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere#536]
Currently, the SS3 favicon is null to avoid 404 errors. We could have an actual image, or use nothing.

**Comment by awead** [comment]
See #537

**Comment by whereismyjetpack** [comment]
Official favicons live here: https://psu.app.box.com/s/4e385x5c4yg6h9kes7bzfy0nxkdwbywy 

I can't find language that requires a favicon. libraries homepage seems to use one

http://visualidentity.psu.edu/content/visual-identity-downloads/index.html

**Comment by srerickson** [comment]
I think we need one.

**Comment by binkylush** [comment]
I don't know of any official PSU style requirements, but agree with @srerickson. We use one on the website and catalog - we should be consistent!

**Comment by srerickson** [comment]
but I still don't see an icon.

**Comment by awead** [comment]
It's there: https://scholarsphere.psu.edu/favicon.ico and it's loaded on page requests, according to the network tab in Firefox.

**Comment by srerickson** [comment]
Must have been a caching issue. I see it now... Thanks.
