### ISSUE TITLE
Delete associated legacy identifiers when deleting works

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere#609]
If a work has any legacy identifiers associated with it, the legacy id for the work is deleted when the work is deleted, but not any legacy ids for associated FileResource objects. The FileResource model has `dependent: :destroy` so it ought to work, but doesn't.

This only affect re-migrating previous works if they've been deleted. For now, it can be done manually, if we delete the identifiers ourselves.

**Comment by rschenk** [comment]
That's.....weird

**Comment by awead** [comment]
We need to verify/reproduce this to be sure.

**Comment by awead** [comment]
I have verified this... The issue is that when you destroy a work, the legacy id for the work is destroyed, but _not_ the legacy ids for its associated files. These are the legacy ids (noids) from the Scholarsphere FileSet objects.

**Comment by awead** [comment]
This will very rarely ever be an issue since we don't create legacy ids for anything other than migration (for now). Since migration is done, we may not need to every worry about this.
